name: rdt
services:
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    develop:
      watch:
        - action: rebuild
          path: ./mongo/Dockerfile
  client:
    build: ./client
    restart: no
  node:
    build: ./node
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./client:/app/node_modules/@simpleview/rd-training-client
    develop:
      watch:
        - action: sync+restart
          path: ./node/lib
          target: /app/lib
        - action: rebuild
          path: ./node/package.json
        - action: rebuild
          path: ./node/Dockerfile
        - action: rebuild
          path: ./client/src
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./client/Dockerfile
  graphql:
    build: ./graphql
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync+restart
          path: ./graphql/lib
          target: /app/lib
        - action: rebuild
          path: ./graphql/package.json
        - action: rebuild
          path: ./graphql/Dockerfile
volumes:
  db_data: