name: rdt
services:
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
  node:
    build: ./node
    ports:
      - "80:80"
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync+restart
          path: ./node/lib
          target: /app/lib
        - action: rebuild
          path: ./node/package.json
volumes:
  db_data: